/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Mobile app design tokens (exact match) ──
        'primary': '#123f5c',
        'primary-teal': '#1a5270',
        'primary-foreground': '#FFFFFF',
        'primary-muted': '#e8f0f5',
        'secondary': '#b9c4eb',
        'accent': '#f2f7ff',
        'background': '#FFFFFF',
        'surface': '#FFFFFF',
        'brand-pink': '#f7f5f0',
        'border-subtle': '#f7f5f0',
        'text-primary': '#000000',
        'destructive': '#DC2626',
        'chart5': '#aa7478',
        'featured-gold': '#d4af37',
        // Semantic aliases for backward compat
        'on-surface': '#000000',
        'on-surface-variant': '#42474d',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#f7f5f0',
        'surface-container': '#f7f5f0',
        'surface-container-high': '#f0eee9',
        'surface-container-highest': '#e4e2dd',
        'surface-dim': '#dbdad5',
        'surface-variant': '#e4e2dd',
        'outline': '#72787e',
        'outline-variant': '#f7f5f0',
        'surface-tint': '#123f5c',
        // Brand aliases (kept for compat)
        'brand-pink-light': '#f7f5f0',
        'brand-teal': '#123f5c',
        'brand-teal-medium': '#1a5270',
        'brand-lavender': '#b9c4eb',
        'brand-cream': '#f7f5f0',
        'brand-rose': '#aa7478',
        'primary-container': '#123f5c',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#e8f0f5',
        'error': '#DC2626',
        'error-container': '#fee2e2',
        'on-error': '#FFFFFF',
        'on-error-container': '#7f1d1d',
        // Legacy aliases (for backward compat with older pages)
        'primary-fixed': '#e8f0f5',
        'secondary-fixed': '#e8f0f5',
        'secondary-container': '#1a5270',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'serif'],
        'body': ['Montserrat', 'sans-serif'],
        'sans': ['Montserrat', 'sans-serif'],
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '999px',
      },
      spacing: {
        'gutter': '16px',
        'section': '64px',
        'margin-desktop': '24px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
}
