export type VendorTagGroupVendorType = 'venue' | 'service_provider';

export interface VendorTagGroup {
  id: string;
  name: string;
  vendorType: VendorTagGroupVendorType;
  tags: string[];
}

// Tag groups sourced from "09.01.2026_Categories tags etc.xlsx" (Vendor & Professional Tags tab).
export const vendorTagGroups: VendorTagGroup[] = [
  {
    id: "venues",
    name: "Venues",
    vendorType: "venue",
    tags: [
      "Indoor",
      "Outdoor",
      "Tables",
      "Chairs",
      "Parking",
      "Disabled access",
      "WiFi",
      "Air conditioning",
      "Heating",
      "Scenic view",
      "Water Features/Fountains",
      "Accommodation",
      "Alcohol allowed",
      "No alcohol",
      "Halaal friendly kitchen",
      "Outside catering allowed",
      "AV available",
      "Stage",
      "Generator",
      "Ablution Facilities",
      "Salaah Room",
      "Chapel",
      "Minimum Guests 10",
    ],
  },
  {
    id: "catering-food",
    name: "Catering (Food)",
    vendorType: "service_provider",
    tags: [
      "Halaal",
      "Vegetarian",
      "Vegan",
      "Gluten free",
      "Non alcohol",
      "Alcohol",
      "On Site Prep",
      "Remote Prep Only",
      "Buffet",
      "Plated",
      "Finger food",
      "Full service",
      "Delivery only",
      "Custom menu",
      "Braai",
    ],
  },
  {
    id: "bar-beverage-services",
    name: "Bar & Beverage Services",
    vendorType: "service_provider",
    tags: [
      "Alcohol",
      "Non alcohol",
      "Mocktails",
      "Licensed",
      "Unlicensed",
      "Cash bar",
      "Open bar",
      "Halaal friendly",
      "Glassware included",
      "Staff included",
    ],
  },
  {
    id: "decor-styling",
    name: "Decor & Styling",
    vendorType: "service_provider",
    tags: [
      "Modern",
      "Traditional",
      "Luxury",
      "Budget",
      "Theme based",
      "Custom design",
      "Furniture included",
      "Linen included",
      "Floral included",
      "Setup included",
      "Teardown included",
      "Indoor",
      "Outdoor",
    ],
  },
  {
    id: "florists",
    name: "Florists",
    vendorType: "service_provider",
    tags: [
      "Fresh flowers",
      "Artificial flowers",
      "Custom arrangements",
      "Installations",
      "On site Setup",
      "Delivery Only",
    ],
  },
  {
    id: "photography",
    name: "Photography",
    vendorType: "service_provider",
    tags: [
      "Weddings",
      "Corporate",
      "Events",
      "Outdoor",
      "Indoor",
      "Travel Available",
      "Local Only",
      "Portfolio Available",
    ],
  },
  {
    id: "videography",
    name: "Videography",
    vendorType: "service_provider",
    tags: [
      "Event filming",
      "Highlights video",
      "Full length video",
      "Drone",
      "Indoor",
      "Outdoor",
      "Travel available",
      "Edited delivery",
      "Raw footage",
    ],
  },
  {
    id: "djs",
    name: "DJs",
    vendorType: "service_provider",
    tags: [
      "Weddings",
      "Corporate",
      "Parties",
      "Family friendly",
      "Adult only",
      "Equipment included",
      "Travel available",
      "Backup equipment",
    ],
  },
  {
    id: "live-bands-musicians",
    name: "Live Bands / Musicians",
    vendorType: "service_provider",
    tags: [
      "Acoustic",
      "Full band",
      "Cultural",
      "Jazz",
      "Pop",
      "Religious friendly",
      "Indoor",
      "Outdoor",
    ],
  },
  {
    id: "mcs-hosts",
    name: "MCs / Hosts",
    vendorType: "service_provider",
    tags: [
      "Formal",
      "Casual",
      "Corporate",
      "Wedding",
      "Multilingual",
      "Family friendly",
      "Comedian",
    ],
  },
  {
    id: "hair-makeup",
    name: "Hair & Makeup",
    vendorType: "service_provider",
    tags: [
      "On site",
      "Salon based",
      "Travel available",
      "Bridal",
      "Event",
      "Long wear",
      "Halaal products",
      "Female only",
      "Male only",
    ],
  },
  {
    id: "event-planners",
    name: "Event Planners",
    vendorType: "service_provider",
    tags: [
      "Full service",
      "Partial planning",
      "Weddings",
      "Corporate",
      "Social events",
      "Budget focused",
      "Luxury",
      "Full planning",
      "On the day",
      "Cultural weddings",
      "Religious friendly",
      "Vendor management",
    ],
  },
  {
    id: "event-production-av",
    name: "Event Production / AV",
    vendorType: "service_provider",
    tags: [
      "Sound",
      "Lighting",
      "Screens",
      "Projectors",
      "Stage",
      "Podium",
      "Indoor",
      "Outdoor",
      "Setup included",
      "Generator",
    ],
  },
  {
    id: "rentals-furniture-equipment",
    name: "Rentals (Furniture & Equipment)",
    vendorType: "service_provider",
    tags: [
      "Tables",
      "Chairs",
      "Tents",
      "Marquees",
      "Crockery",
      "Glassware",
      "Linen",
      "Delivery included",
      "Setup included",
    ],
  },
  {
    id: "photo-booths",
    name: "Photo Booths",
    vendorType: "service_provider",
    tags: [
      "Digital",
      "Printed",
      "Props included",
      "Custom branding",
      "Instant sharing",
      "Setup included",
    ],
  },
  {
    id: "security-services",
    name: "Security Services",
    vendorType: "service_provider",
    tags: [
      "Event security",
      "Crowd control",
      "Armed",
      "Unarmed",
      "Indoor",
      "Outdoor",
      "Licensed",
    ],
  },
  {
    id: "staffing-waiters-bar-crew",
    name: "Staffing (Waiters / Bar / Crew)",
    vendorType: "service_provider",
    tags: [
      "Trained staff",
      "Halaal compliant",
      "Uniformed",
      "Short shift",
      "Full day",
      "Travel available",
    ],
  },
  {
    id: "transport-parking",
    name: "Transport & Parking",
    vendorType: "service_provider",
    tags: [
      "Shuttle",
      "Guest transport",
      "VIP transport",
      "Valet",
      "Secure parking",
      "Accessible vehicles",
    ],
  },
  {
    id: "support-compliance",
    name: "Support & Compliance",
    vendorType: "service_provider",
    tags: [
      "Insured",
      "Registered business",
      "Flexible cancellation",
      "Last minute available",
      "Weekday discounts",
    ],
  },
  {
    id: "cakes-desserts",
    name: "Cakes & Desserts",
    vendorType: "service_provider",
    tags: [
      "Halaal",
      "Custom design",
      "Cupcakes",
      "Wedding cakes",
      "Birthday cakes",
      "Dessert tables",
      "Delivery available",
      "Setup included",
    ],
  },
  {
    id: "kids-entertainment",
    name: "Kids Entertainment",
    vendorType: "service_provider",
    tags: [
      "Face painting",
      "Jumping castles",
      "Clowns",
      "Magicians",
      "Mascots",
      "Party hosts",
      "Age specific",
      "Indoor",
      "Outdoor",
      "Supervised",
    ],
  },
  {
    id: "cultural-performers",
    name: "Cultural Performers",
    vendorType: "service_provider",
    tags: [
      "Traditional dance",
      "Cultural music",
      "Weddings",
      "Indoor",
      "Outdoor",
    ],
  },
  {
    id: "sound-engineers",
    name: "Sound Engineers",
    vendorType: "service_provider",
    tags: [
      "Live sound",
      "DJ support",
      "Band support",
      "Indoor",
      "Outdoor",
      "Equipment included",
      "Backup gear",
    ],
  },
  {
    id: "lighting-specialists",
    name: "Lighting Specialists",
    vendorType: "service_provider",
    tags: [
      "Ambient lighting",
      "Stage lighting",
      "Mood lighting",
      "Outdoor",
      "Indoor",
      "Generator compatible",
    ],
  },
  {
    id: "staging-rigging",
    name: "Staging & Rigging",
    vendorType: "service_provider",
    tags: [
      "Stage build",
      "Truss",
      "Podium",
      "Indoor",
      "Outdoor",
      "Safety certified",
      "Setup included",
    ],
  },
  {
    id: "tents-marquees",
    name: "Tents & Marquees",
    vendorType: "service_provider",
    tags: [
      "Frame tents",
      "Peg and pole",
      "Clear roof",
      "Flooring included",
      "Sidewalls",
    ],
  },
  {
    id: "furniture-hire",
    name: "Furniture Hire",
    vendorType: "service_provider",
    tags: [
      "Lounge furniture",
      "Cocktail tables",
      "Dining tables",
      "Chairs",
      "Delivery included",
      "Setup included",
    ],
  },
  {
    id: "linen-draping",
    name: "Linen & Draping",
    vendorType: "service_provider",
    tags: [
      "Tablecloths",
      "Chair covers",
      "Backdrops",
      "Ceiling draping",
      "Colour options",
      "Setup included",
    ],
  },
  {
    id: "signage-printing",
    name: "Signage & Printing",
    vendorType: "service_provider",
    tags: [
      "Seating charts",
      "Welcome signs",
      "Banners",
      "Branding",
      "Custom design",
      "Rush orders",
    ],
  },
  {
    id: "event-cleaning",
    name: "Event Cleaning",
    vendorType: "service_provider",
    tags: [
      "Pre event",
      "Post event",
      "During event",
      "Waste removal",
      "Eco friendly",
    ],
  },
  {
    id: "waste-sanitation",
    name: "Waste & Sanitation",
    vendorType: "service_provider",
    tags: [
      "Portable toilets",
      "Luxury restrooms",
      "Handwash stations",
      "Servicing included",
    ],
  },
  {
    id: "power-generators",
    name: "Power & Generators",
    vendorType: "service_provider",
    tags: [
      "Silent generators",
      "Backup power",
      "Loadshedding ready",
      "Outdoor events",
    ],
  },
  {
    id: "fireworks-effects",
    name: "Fireworks & Effects",
    vendorType: "service_provider",
    tags: [
      "Fireworks",
      "Cold sparks",
      "Indoor approved",
      "Outdoor only",
      "Drone Displays",
    ],
  },
  {
    id: "audio-visual-recording",
    name: "Audio Visual Recording",
    vendorType: "service_provider",
    tags: [
      "Live streaming",
      "Hybrid events",
      "Recording only",
      "Corporate ready",
    ],
  },
  {
    id: "digital-invitations-rsvps",
    name: "Digital Invitations & RSVPs",
    vendorType: "service_provider",
    tags: [
      "Online RSVP",
      "Guest tracking",
      "Seating management",
      "Mobile friendly",
    ],
  },
  {
    id: "accommodation-providers",
    name: "Accommodation Providers",
    vendorType: "service_provider",
    tags: [
      "Group bookings",
      "Shuttle coordination",
      "On site Accommodation",
      "Nearby",
    ],
  },
  {
    id: "event-consultants",
    name: "Event Consultants",
    vendorType: "service_provider",
    tags: [
      "Concept development",
      "Budget planning",
      "Sourcing",
      "Timeline creation",
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    vendorType: "service_provider",
    tags: [
      "Team Building Games",
      "Celebrity Hosts",
      "Clowns",
      "Comedians",
      "Content Creators & Influencers",
      "Dancers",
      "Impersonators",
      "Instrumentalists (Violinist, Pianist)",
      "MC's",
      "Singers & Bands",
      "Speciality Acts (Acrobats, Fire Eaters, Jugglers, Puppeteers, Ventriloquists)",
    ],
  },
];

// Deduplicated flat list of every tag across all groups.
export const allVendorTags: string[] =
  vendorTagGroups.flatMap((g) => g.tags).filter((t, i, arr) => arr.indexOf(t) === i);
