export const venueTypes = [
  "Auditoriums",
  "Ballrooms",
  "Banquet halls",
  "Beach venues",
  "Boutiques",
  "Clubhouses",
  "Conference Centres",
  "Convention/Expo Centres",
  "Fairgrounds/Open Fields",
  "Farms",
  "Gardens",
  "Hotels",
  "Industrial venues",
  "Lodges",
  "Resorts",
  "Restaurants",
  "Rooftops",
  "Sports Courts & Arenas",
  "Theatres",
  "Wine estates"
];

export const amenitiesList = [
  "Ablution Facilities",
  "Accommodation / Guest Rooms",
  "Air-conditioning",
  "AV Connectivity",
  "Baby Changing Facilities",
  "Balcony / Stoep / Terrace",
  "Bar / Drinks Station",
  "Board Room Table & Chairs",
  "Braai Area",
  "Bridal / Groom Suite",
  "Tables & Chairs Available",
  "Changing/Cloak Rooms",
  "Chappel",
  "Cleaning Services Available",
  "Cutlery & Crockery Available",
  "Dance floor",
  "Generator & Back Up Power",
  "Flexible with special requests",
  "Free Parking",
  "Full-Service Staffing",
  "Gardens",
  "Green Room",
  "Halaal",
  "Heating System",
  "High ceilings",
  "Indoor & Outdoor Mix Space",
  "Indoor Only Space",
  "Kitchen - Basins & Prep Tables",
  "Kitchen - Full Amenities",
  "LED Screen",
  "Ambiant Lighting",
  "Linen & Tablecloths Available",
  "Loading / Unloading Area",
  "Lounge & Networking Zones",
  "Marquee / Tent / Gazebo Spaces",
  "Multiple Hall Options at Venue",
  "Natural lighting",
  "Nature Setting",
  "On Site Venue Manager",
  "On-Site Catering",
  "Open Fields",
  "Open indoor/outdoor spaces",
  "Outdoor Only Space",
  "Package Deal Options",
  "Petting Zoo / Animal Park",
  "Pickup/Drop Off Zone",
  "Kids Play areas",
  "Plug Points / Charging Ports",
  "Podium Available",
  "Security Guards",
  "Swimming Pool",
  "Salaah Prayer Facilities",
  "Projectors",
  "Digital White Boards",
  "Refrigerator / Cooler Room",
  "Restrooms / Toilets",
  "Scenic Views",
  "Secure Parking",
  "Gated Access",
  "Sound & Mic system",
  "Stage Available",
  "Storage Space",
  "Water Features/Fountains",
  "Wheel Chair Accessable",
  "WiFi - high speed",
  "Audio Visual Recording Equipment Available",
  "Meeting Rooms",
  "Hybrid Audio Visual Equipment"
];

export const venueCapacityOptions = [
  "Under 50",
  "Under 200",
  "Under 500",
  "Under 1000",
  "Under 2000",
  "2000 and More"
];

export const eventTypes = [
  "Anniversary",
  "Graduation/Awards",
  "Baby Shower",
  "Birthday - Adult",
  "Birthday - Kiddies",
  "Bridal Shower",
  "Community Fair",
  "Live Show/Concert",
  "Conference / Seminar",
  "Corporate Party",
  "Cultural Celebration",
  "Expo",
  "Festival",
  "Fundraiser",
  "Product Launch",
  "Market",
  "Sports Tournament",
  "Teambuilding",
  "Wedding",
  "Reunion"
];
