export const VENUE_TYPES = [
  'Auditoriums',
  'Ballrooms',
  'Banquet halls',
  'Beach venues',
  'Boutiques',
  'Clubhouses',
  'Conference Centres',
  'Convention/Expo Centres',
  'Fairgrounds/Open Fields',
  'Farms',
  'Gardens',
  'Hotels',
  'Industrial venues',
  'Lodges',
  'Resorts',
  'Restaurants',
  'Rooftops',
  'Sports Courts & Arenas',
  'Theatres',
  'Wine estates',
];

export const VENDOR_CATEGORIES = [
  'Audio & Visual',
  'Catering',
  'Decor',
  'Entertainment',
  'Event Planning',
  'Florists',
  'Hair & Makeup',
  'Lighting',
  'Music & DJs',
  'Photography',
  'Photo Booths',
  'Security',
  'Staffing',
  'Stationery',
  'Transport',
  'Videography',
  'Wedding Planning',
  'Cakes & Desserts',
  'Bar & Beverage',
  'Furniture Rental',
  'Tents & Structures',
  'Wellness & Beauty',
];

export const VENDOR_SUBCATEGORIES: Record<string, string[]> = {
  'Audio & Visual': ['Sound Systems', 'Projectors', 'Microphones', 'LED Screens', 'Stage Lighting'],
  'Catering': ['Buffet', 'Plated', 'Cocktail', 'BBQ', 'Dietary Specific', 'Corporate Catering'],
  'Decor': ['Floral Decor', 'Table Settings', 'Lighting Decor', 'Themed Decor', 'Backdrops'],
  'Entertainment': ['Live Bands', 'DJs', 'Magicians', 'Comedians', 'Cultural Performers', 'Fireworks'],
  'Photography': ['Wedding', 'Corporate', 'Event', 'Product', 'Aerial', 'Portrait'],
  'Videography': ['Wedding Films', 'Corporate Videos', 'Live Streaming', 'Highlight Reels'],
  'Music & DJs': ['Wedding DJ', 'Corporate DJ', 'Party DJ', 'Live Music', 'MC Services'],
};

export const AMENITIES = [
  'Ablution Facilities',
  'Accommodation / Guest Rooms',
  'Air-conditioning',
  'Ambiant Lighting',
  'Audio Visual Recording Equipment Available',
  'AV Connectivity',
  'Baby Changing Facilities',
  'Balcony / Stoep / Terrace',
  'Bar / Drinks Station',
  'Board Room Table & Chairs',
  'Braai Area',
  'Bridal / Groom Suite',
  'Changing/Cloak Rooms',
  'Chappel',
  'Cleaning Services Available',
  'Cutlery & Crockery Available',
  'Dance floor',
  'Digital White Boards',
  'Flexible with special requests',
  'Free Parking',
  'Full-Service Staffing',
  'Gardens',
  'Gated Access',
  'Generator & Back Up Power',
  'Green Room',
  'Halaal',
  'Heating System',
  'High ceilings',
  'Hybrid Audio Visual Equipment',
  'Indoor & Outdoor Mix Space',
  'Indoor Only Space',
  'Kids Play areas',
  'Kitchen - Basins & Prep Tables',
  'Kitchen - Full Amenities',
  'LED Screen',
  'Linen & Tablecloths Available',
  'Loading / Unloading Area',
  'Lounge & Networking Zones',
  'Marquee / Tent / Gazebo Spaces',
  'Meeting Rooms',
  'Multiple Hall Options at Venue',
  'Natural lighting',
  'Nature Setting',
  'On Site Venue Manager',
  'On-Site Catering',
  'Open Fields',
  'Open indoor/outdoor spaces',
  'Outdoor Only Space',
  'Package Deal Options',
  'Petting Zoo / Animal Park',
  'Pickup/Drop Off Zone',
  'Plug Points / Charging Ports',
  'Podium Available',
  'Projectors',
  'Refrigerator / Cooler Room',
  'Restrooms / Toilets',
  'Salaah Prayer Facilities',
  'Scenic Views',
  'Secure Parking',
  'Security Guards',
  'Sound & Mic system',
  'Stage Available',
  'Storage Space',
  'Swimming Pool',
  'Tables & Chairs Available',
  'Water Features/Fountains',
  'Wheel Chair Accessable',
  'WiFi - high speed',
];

export const CAPACITY_BANDS = [
  { label: 'Any capacity', value: '' },
  { label: 'Under 50', value: '0-50' },
  { label: 'Under 200', value: '0-200' },
  { label: 'Under 500', value: '0-500' },
  { label: 'Under 1000', value: '0-1000' },
  { label: 'Under 2000', value: '0-2000' },
  { label: '2000+', value: '2000-999999' },
];

export const SORT_OPTIONS = [
  { label: 'Name (A-Z)', value: 'name-asc' },
  { label: 'Name (Z-A)', value: 'name-desc' },
  { label: 'Rating (High-Low)', value: 'rating-desc' },
  { label: 'Rating (Low-High)', value: 'rating-asc' },
  { label: 'Price (Low-High)', value: 'price-asc' },
  { label: 'Price (High-Low)', value: 'price-desc' },
];

export const MIN_RATING_OPTIONS = [
  { label: 'Any rating', value: 0 },
  { label: '1 star & up', value: 1 },
  { label: '2 stars & up', value: 2 },
  { label: '3 stars & up', value: 3 },
  { label: '4 stars & up', value: 4 },
  { label: '5 stars', value: 5 },
];

export const PROVINCES = [
  'Gauteng',
  'Western Cape',
  'KwaZulu-Natal',
  'Eastern Cape',
  'Free State',
  'Mpumalanga',
  'Limpopo',
  'North West',
  'Northern Cape',
];

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Gauteng': [
    'Alberton', 'Alexandra', 'Benoni', 'Boksburg', 'Brakpan', 'Bronkhorstspruit',
    'Carletonville', 'Centurion', 'Daveyton', 'Edenvale', 'Evaton', 'Fourways',
    'Germiston', 'Heidelberg', 'Isando', 'Johannesburg', 'Katlehong', 'Kempton Park',
    'Krugersdorp', 'Lenasia', 'Mabopane', 'Mamelodi', 'Melville', 'Meyerton',
    'Midrand', 'Ormonde', 'Parktown', 'Pretoria', 'Protea Glen', 'Randburg',
    'Randfontein', 'Roodepoort', 'Rosebank', 'Sandton', 'Sebokeng', 'Sharpeville',
    'Soweto', 'Springs', 'Tembisa', 'Tsakane', 'Vanderbijlpark', 'Vereeniging',
    'Vosloorus', 'Wattville', 'Westonaria', 'Yeoville'
  ],
  'Western Cape': [
    'Athlone', 'Atlantis', 'Bellville', 'Bloubergstrand', 'Brackenfell', 'Beaufort West',
    'Bredasdorp', 'Caledon', 'Cape Town', 'Ceres', 'Claremont', 'Durbanville',
    'Fish Hoek', 'Franschhoek', 'Gansbaai', 'George', 'Grabouw', "Gordon's Bay",
    'Hermanus', 'Hout Bay', 'Khayelitsha', 'Knysna', 'Kuils River', 'Langebaan',
    'Lansdowne', 'Malmesbury', 'Milnerton', 'Mitchells Plain', 'Montagu', 'Mossel Bay',
    'Muizenberg', 'Newlands', 'Observatory', 'Oudtshoorn', 'Paarl', 'Parow',
    'Pinelands', 'Plettenberg Bay', 'Robertson', 'Rondebosch', 'Saldanha Bay', 'Sea Point',
    'Simons Town', 'Somerset West', 'Stellenbosch', 'Strand', 'Swellendam', 'Table View',
    'Vredenburg', 'Wellington', 'Worcester', 'Wynberg'
  ],
  'KwaZulu-Natal': [
    'Amanzimtoti', 'Ballito', 'Chatsworth', 'Dundee', 'Durban', 'Empangeni',
    'Eshowe', 'Estcourt', 'Hillcrest', 'Hluhluwe', 'Howick', 'Ixopo',
    'Kloof', 'Kokstad', 'La Lucia', 'Ladysmith', 'Margate', 'Mtunzini',
    'Newcastle', 'Phoenix', 'Pietermaritzburg', 'Pinetown', 'Port Edward', 'Port Shepstone',
    'Queensburgh', 'Richards Bay', 'Scottburgh', 'Stanger', 'Tongaat', 'Umhlanga',
    'Umlazi', 'Vryheid', 'Westville'
  ],
  'Eastern Cape': [
    'Adelaide', 'Alexandria', 'Aliwal North', 'Bathurst', 'Bhisho', 'Burgersdorp',
    'Butterworth', 'Cradock', 'Despatch', 'East London', 'Fort Beaufort', 'Graaff-Reinet',
    'Grahamstown', 'Humansdorp', 'Jeffreys Bay', 'King William\'s Town', 'Kirkwood', 'Komani',
    'Komga', 'Lady Frere', 'Matatiele', 'Middleburg', 'Mthatha', 'Port Alfred',
    'Port Elizabeth', 'Queenstown', 'Somerset East', 'St Francis Bay', 'Sterkspruit', 'Uitenhage'
  ],
  'Free State': [
    'Bethlehem', 'Bloemfontein', 'Bothaville', 'Clarens', 'Clocolan', 'Ficksburg',
    'Fouriesburg', 'Frankfort', 'Harrismith', 'Heilbron', 'Hennenman', 'Kestell',
    'Koffiefontein', 'Kroonstad', 'Ladybrand', 'Lindley', 'Marquard', 'Odendaalsrus',
    'Parys', 'Phuthaditjhaba', 'Reitz', 'Sasolburg', 'Senekal', 'Trompsburg', 'Villiers',
    'Virginia', 'Vrede', 'Vredefort', 'Welkom', 'Winburg'
  ],
  'Limpopo': [
    'Bela-Bela', 'Bochum', 'Burgersfort', 'Dendron', 'Duiwelskloof', 'Giyani',
    'Groblersdal', 'Haenertsburg', 'Hoedspruit', 'Lebowakgomo', 'Lephalale', 'Letsitele',
    'Louis Trichardt', 'Makhado', 'Malamulele', 'Marble Hall', 'Messina', 'Modimolle',
    'Modjadjiskloof', 'Mokopane', 'Musina', 'Mutale', 'Namakgale', 'Nkowakowa',
    'Nylstroom', 'Phalaborwa', 'Polokwane', 'Seshego', 'Thabazimbi', 'Thohoyandou',
    'Tzaneen', 'Vuwani'
  ],
  'Mpumalanga': [
    'Acornhoek', 'Balfour', 'Barberton', 'Belfast', 'Bethal', 'Bushbuckridge',
    'Carolina', 'Delmas', 'Dullstroom', 'Ermelo', 'Graskop', 'Hazyview',
    'Hendrina', 'KaBokweni', 'Kinross', 'Komatipoort', 'KwaMhlanga', 'Lydenburg',
    'Machadodorp', 'Malelane', 'Middelburg', 'Nelspruit', 'Piet Retief', "Pilgrim's Rest",
    'Sabie', 'Secunda', 'Siyabuswa', 'Standerton', 'Steve Tshwete', 'Volksrust',
    'Wakkerstroom', 'Waterval Boven', 'White River', 'Witbank', 'eMalahleni'
  ],
  'North West': [
    'Bapong', 'Bloemhof', 'Brits', 'Christiana', 'Coligny', 'Delareyville',
    'Ga-Rankuwa', 'Groot Marico', 'Hartbeespoort', 'Itsoseng', 'Klerksdorp', 'Koster',
    'Lehurutshe', 'Lichtenburg', 'Madikwe', 'Mahikeng', 'Marikana', 'Mmabatho',
    'Mogwase', 'Mooinooi', 'Orkney', 'Potchefstroom', 'Rustenburg', 'Sannieshof',
    'Schweizer-Reneke', 'Stilfontein', 'Sun City', 'Swartruggens', 'Taung', 'Ventersdorp',
    'Vryburg', 'Wolmaransstad', 'Zeerust'
  ],
  'Northern Cape': [
    'Aggeneys', 'Barkly West', 'Brandvlei', 'Britstown', 'Calvinia', 'Campbell',
    'Carnarvon', 'Colesberg', 'Daniëlskuil', 'De Aar', 'Douglas', 'Fraserburg',
    'Griquatown', 'Groblershoop', 'Hartswater', 'Hopetown', 'Kakamas', 'Kathu',
    'Kenhardt', 'Kimberley', 'Koopmansfontein', 'Kuruman', 'Loxton', 'Niekerkshoop',
    'Olifantshoek', 'Orania', 'Pofadder', 'Postmasburg', 'Prieska', 'Richmond',
    'Springbok', 'Strydenburg', 'Sutherland', 'Upington', 'Victoria West', 'Vioolsdrif',
    'Williston'
  ],
};
