/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system colors
        'primary': '#002940',
        'primary-container': '#123f5c',
        'on-primary': '#ffffff',
        'on-primary-container': '#83aacc',
        'primary-fixed': '#cbe6ff',
        'primary-fixed-dim': '#a3cbee',
        'inverse-primary': '#a3cbee',
        'secondary': '#306382',
        'secondary-container': '#a9dbfe',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#2c617f',
        'secondary-fixed': '#c7e7ff',
        'secondary-fixed-dim': '#9bcdf0',
        'tertiary': '#1a2544',
        'tertiary-container': '#303b5b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#9aa5cb',
        'tertiary-fixed': '#dae1ff',
        'tertiary-fixed-dim': '#bac5ec',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'surface-variant': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#42474d',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        'background': '#fbf9f4',
        'on-background': '#1b1c19',
        'outline': '#72787e',
        'outline-variant': '#c2c7ce',
        'surface-tint': '#3b6281',
        // Brand alias colors (from theme.ts)
        'brand-pink': '#f7f5f0',
        'brand-pink-light': '#f7f5f0',
        'brand-teal': '#123f5c',
        'brand-teal-medium': '#1a5270',
        'brand-lavender': '#b9c4eb',
        'brand-cream': '#f7f5f0',
        'brand-rose': '#aa7478',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'serif'],
        'body': ['Montserrat', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '16px',
        'section': '64px',
        'margin-desktop': '24px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
}
